---

- name: copy webhook file
  copy:
    src: "files/webhook"
    dest: "/usr/local/bin/webhook"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0740
  notify:
    - restart webhook-audit
    - restart webhook-log
# 设置为节点的hostname,如果没开启修改主机名，需要手动修改
  when:  ansible_hostname == "DCZ-2007FC107U34-L17-A05"

- name: Create the webhook-audit server systemd config
  template:
    src: webhook-audit.service.j2
    dest: "/etc/systemd/system/webhook-audit.service"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0644
  when:  ansible_hostname == "node1"
  notify:
    - reload webhook-audit systemd
    - restart webhook-audit

- name: Create the webhook-log server systemd config
  template:
    src: webhook-log.service.j2
    dest: "/etc/systemd/system/webhook-log.service"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0644
  when:  ansible_hostname == "node1"
  notify:
    - reload webhook-log systemd
    - restart webhook-log

- name: Enable and start the webhook-log service
  service:
    name: webhook-log
    enabled: true
    state: started

- name: Enable and start the webhook-audit service
  service:
    name: webhook-audit
    enabled: true
    state: started