---
- include_tasks: init-server.yml
  when: minio_init_server

- include_tasks: install-server.yml
  when: minio_install_server

- include_tasks: install-client.yml
  when: minio_install_client

- include_tasks: config-cluster.yml
  when: minio_install_client