---
# handlers file for minio

- name: reload minio systemd
  systemd:
    name: minio
    daemon_reload: True

- name: restart minio
  service:
    name: minio
    state: restarted
  notify: Check MinIO WebUI

- name: Check MinIO WebUI
  uri:
    url: "{{ minio_connection_type }}://{{ minio_hostname }}:9000/minio/login"
    status_code: 200
    headers:
      User-Agent: "Mozilla/5.0"
    validate_certs: false
  register: login_page
  until: login_page.status == 200
  retries: 10
  delay: 1

- name: reload webhook-audit systemd
  systemd:
    name: webhook-audit
    daemon_reload: True

- name: restart webhook-audit
  service:
    name: webhook-audit
    state: restarted

- name: reload webhook-log systemd
  systemd:
    name: webhook-log
    daemon_reload: True

- name: restart webhook-log
  service:
    name: webhook-log
    state: restarted